quarto-required: ">= 1.8.27"

project:
  type: default
  title: European digital identity

format:
  ieee-html:
    output-file: index.html
  hikmah-pdf:
    output-file: index.pdf

embed-resources: true
self-contained: true
self-contained-math: true

code-links: false
format-links: false
notebook-links: false
other-links: false

pdf-engine: xelatex
latex-tinytex: true
latex-auto-install: true
latex-auto-mk: true
latex-clean: true
keep-tex: true
